// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ZJwTVkilOSTGkN9jKq98hWSpnO22Shw',
    appId: '1:116254805473:web:f689f1f3c30e6af9dd16a0',
    messagingSenderId: '116254805473',
    projectId: 'draineye-860f6',
    authDomain: 'draineye-860f6.firebaseapp.com',
    storageBucket: 'draineye-860f6.firebasestorage.app',
    measurementId: 'G-HSR4YPCLW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSwkc0uwagPtb2VpoHPVM9W7T3UceUCGs',
    appId: '1:116254805473:android:abda996373c47fd3dd16a0',
    messagingSenderId: '116254805473',
    projectId: 'draineye-860f6',
    storageBucket: 'draineye-860f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-c0TVmZquUO-ShDYdwepMEisjve5qaH8',
    appId: '1:116254805473:ios:4115d07e9330aa29dd16a0',
    messagingSenderId: '116254805473',
    projectId: 'draineye-860f6',
    storageBucket: 'draineye-860f6.firebasestorage.app',
    iosClientId: '116254805473-0h7gitvpdtqv4qfd3qrb1oeh122ujccu.apps.googleusercontent.com',
    iosBundleId: 'com.example.drainEye',
  );
}
